---
- name: Resolve inventory
  ansible.builtin.include_tasks: manage_inventory.yaml

- name: Retrieve a repository from a distant location and make it available locally
  ansible.builtin.include_tasks: retrieve.yaml
  when: data_store.scm is defined

- name: Include file write task
  ansible.builtin.include_tasks: manage_inventory.yaml

- name: Get list of files
  ansible.builtin.find:
    paths: "{{ deploy_inventory_path }}/host_vars/{{ inventory_hostname }}"
    recurse: false
    patterns: "*.yaml"
    file_type: file
  register: deploy_found_directories

- name: Include configure task
  ansible.builtin.include_tasks: apply_configuration.yaml
  loop: "{{ deploy_found_directories.files }}"
  loop_control:
    loop_var: file
    label: "{{ file.path | basename }}"
