---
- name: Set default host vars path
  ansible.builtin.set_fact:
    deploy_inventory_directory: "."
  when: data_store.local is not defined

- name: Set default host vars path
  ansible.builtin.set_fact:
    deploy_inventory_directory: "{{ data_store['local'] }}"
  when: data_store['local'] is defined

- name: Set default path
  ansible.builtin.set_fact:
    deploy_inventory_path: "{{ deploy_repository['path'] }}"
  when: deploy_repository is defined

- name: Set default path
  ansible.builtin.set_fact:
    deploy_inventory_path: "{{ deploy_inventory_directory }}"
  when: deploy_repository is not defined
