---
- name: Retrieve the host vars with token access (if provided)
  ansible.scm.git_retrieve:
    origin:
      url: "{{ data_store['scm']['origin']['url'] }}"
      token: "{{ data_store['scm']['origin']['token'] | d(None) }}"
    parent_directory: "{{ data_store.scm.parent_directory | default(deploy_inventory_directory) }}"
  changed_when: false
  register: deploy_result

- name: Update data store path
  ansible.builtin.set_fact:
    deploy_repository: "{{ deploy_result }}"

- name: Update Inventory Path
  ansible.builtin.set_fact:
    deploy_inventory_path: "{{ deploy_repository['path'] }}"
