---
authors:
  - Rohit Thakur (@rohitthakur2590)
dependencies:
  "ansible.netcommon": ">=6.0.0"
  "ansible.utils": ">=3.0.0"
  "ansible.scm": ">=2.0.0"
license_file: LICENSE
name: base
description: Ansible Network Collection provides platform-agnostic resource management for given network OS.
namespace: network
readme: README.md
repository: https://github.com/redhat-cop/network.base
issues: https://github.com/redhat-cop/network.base/issues
tags: [networking]
version: 5.0.0
