---
- name: Get the supported resource modules
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
  register: detect_network_resources_list

- name: Set resources
  ansible.builtin.set_fact:
    detect_resources: "{{ detect_network_resources_list['modules'] }}"
  when: detect_resources is undefined

- name: Set Network resources
  ansible.builtin.set_fact:
    detect_network_resources: "{{ detect_network_resources_list['modules'] | ansible.utils.param_list_compare(detect_resources) }}"

- name: Resolve inventory
  ansible.builtin.include_tasks: manage_inventory.yaml

- name: Retrieve a repository from a distant location and make it available locally
  ansible.builtin.include_tasks: retrieve.yaml
  when: data_store['scm'] is defined

- name: Get list of SOT files
  ansible.builtin.find:
    paths: "{{ detect_inventory_path }}/host_vars/{{ inventory_hostname }}"
    recurse: false
    patterns: "*.yaml"
    file_type: file
  register: detect_found_directories

- name: Set default state as 'overridden'
  ansible.builtin.set_fact:
    detect_state: 'overridden'
  when: detect_state is not defined

- name: Include check_drift task
  ansible.builtin.include_tasks: check_drift.yaml
  loop: "{{ detect_found_directories.files }}"
  loop_control:
    loop_var: rms
    label: "{{ rms.path | basename }}"
  when:
    - detect_resources is defined

- name: Detect drift
  ansible.builtin.debug:
    msg: "There is no configuration drift found"
