---
- name: Set default host vars path
  ansible.builtin.set_fact:
    detect_inventory_directory: "."
  when: data_store.local is not defined

- name: Set default host vars path
  ansible.builtin.set_fact:
    detect_inventory_directory: "{{ data_store['local'] }}"
  when: data_store['local'] is defined

- name: Set default path
  ansible.builtin.set_fact:
    detect_inventory_path: "{{ detect_repository['path'] }}"
  when: detect_repository is defined

- name: Set default path
  ansible.builtin.set_fact:
    detect_inventory_path: "{{ detect_inventory_directory }}"
  when: detect_repository is not defined
