---
- name: Get the supported resource modules
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
  register: network_resources_list

- name: Set resources
  ansible.builtin.set_fact:
    resources: "{{ network_resources_list['modules'] }}"
  when: resources is undefined

- name: Set Network resources
  ansible.builtin.set_fact:
    network_resources: "{{ network_resources_list['modules'] | ansible.utils.param_list_compare(resources) }}"

- name: Resolve inventory
  ansible.builtin.include_tasks: includes/inventory.yaml

- name: Retrieve a repository from a distant location and make it available locally
  ansible.builtin.include_tasks: includes/retrieve.yaml
  when: data_store.scm is defined

- name: Get list of SOT files
  ansible.builtin.find:
    paths: "{{ inventory_path }}/host_vars/{{ inventory_hostname }}"
    recurse: false
    patterns: "*.yaml"
    file_type: file
  register: found_directories

- name: Set default state as 'overridden'
  ansible.builtin.set_fact:
    state: "overridden"
  when: state is not defined

- name: Include check_drift task
  ansible.builtin.include_tasks: includes/check_drift.yml
  loop: "{{ found_directories.files }}"
  loop_control:
    loop_var: rms
    label: "{{ rms.path | basename }}"
  when:
    - resources is defined

- name: Detect drift
  ansible.builtin.debug:
    msg: "There is no configuration drift found"
