---
- name: Resolve inventory
  ansible.builtin.include_tasks: includes/inventory.yaml

- name: Retrieve host vars and save locally
  ansible.builtin.include_tasks: includes/retrieve.yaml
  when: data_store.scm is defined

- name: Get list of SOT files
  ansible.builtin.find:
    paths: "{{ inventory_path }}/host_vars/{{ inventory_hostname }}"
    recurse: false
    patterns: "*.yaml"
    file_type: file
  register: found_directories

- name: Set state as overridden to restore config
  ansible.builtin.set_fact:
    state: overridden
  when: state is not defined

- name: Rectify drift
  ansible.builtin.include_tasks: includes/configure.yaml
  loop: "{{ found_directories.files }}"
  loop_control:
    loop_var: file
    label: "{{ file.path | basename }}"
