---
- name: Set facts
  ansible.builtin.set_fact:
    name: "{{ ansible_network_os }}_{{ (file.path | basename).split('.') | first }}"
    resource: "{{ (file.path | basename).split('.') | first }}"
    lst: "{{ (file.path | basename).split('.') | first }}"

- name: Grab the resource facts
  ansible.builtin.include_vars:
    file: "{{ file.path }}"
    name: module_vars

- name: Set default state
  ansible.builtin.set_fact:
    state: 'merged'
  when: state is not defined

- name: Include tasks
  ansible.builtin.include_tasks: includes/edit_resource.yaml
  when:
    - resources is defined

- name: Apply configuration
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
    name: "{{ name.split('.')[-1] }}"
    config: "{{ module_vars[resource] }}"
    state: "{{ state }}"
  when:
    - resources is not defined
