---
- name: Publish the persist changes
  ansible.scm.git_publish:
    path: "{{ repository['path'] }}"
    timeout: 120
  when: data_store.scm.origin.token is undefined

- name: Publish the changes
  ansible.scm.git_publish:
    path: "{{ repository['path'] }}"
    token: "{{ data_store['scm']['origin']['token'] }}"
    user: "{{ data_store['scm']['origin']['user'] }}"
    timeout: 120
  when: data_store.scm.origin.token is defined
