---
- name: Set default host vars path
  ansible.builtin.set_fact:
    remediate_inventory_directory: "."
  when: data_store.local is not defined

- name: Set default host vars path
  ansible.builtin.set_fact:
    remediate_inventory_directory: "{{ data_store['local'] }}"
  when: data_store['local'] is defined

- name: Set default path
  ansible.builtin.set_fact:
    remediate_inventory_path: "{{ remediate_repository['path'] }}"
  when: remediate_repository is defined

- name: Set default path
  ansible.builtin.set_fact:
    remediate_inventory_path: "{{ remediate_inventory_directory }}"
  when: remediate_repository is not defined
