---
- name: Set supported platform list
  ansible.builtin.set_fact:
    supported_platforms:
      - "ios"
      - "junos"
      - "eos"
      - "nxos"
      - "iosxr"
      - "vyos"

- name: Conditional test
  ansible.builtin.include_tasks: "unsupported_platform.yaml"
  when: ansible_network_os.split('.')[-1] not in supported_platforms
