---
- name: Set default host vars path
  ansible.builtin.set_fact:
    persist_inventory_directory: "."
  when: data_store.local is not defined

- name: Set default host vars path
  ansible.builtin.set_fact:
    persist_inventory_directory: "{{ data_store['local'] }}"
  when: data_store['local'] is defined

- name: Set default path
  ansible.builtin.set_fact:
    persist_inventory_path: "{{ persist_repository['path'] }}"
  when: persist_repository is defined

- name: Set default path
  ansible.builtin.set_fact:
    persist_inventory_path: "{{ persist_inventory_directory }}"
  when: persist_repository is not defined
